---

- name: "Setup Fedora"
  hosts: localhost
  connection: local
  vars:
    root_dir: "{{ ansible_local.system_setup.general.root_dir }}"
    dotfiles_dir: "{{ ansible_local.system_setup.general.dotfiles_dir }}"
  tasks:
    - include: fedora/main.yml
